{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "5babc6c9_f3fcf468",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2023-09-07T20:40:40Z",
      "side": 1,
      "message": "(i defer to cferris/danalbert for python reviews...)",
      "revId": "85f6bd8ed5a6d8d35ed81df2bd796e93cdc2d171",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "922644a5_1b2b851a",
        "filename": "scripts/acov-llvm.py",
        "patchSetId": 2
      },
      "lineNbr": 196,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2023-09-07T20:40:40Z",
      "side": 1,
      "message": "this seems unrelated?",
      "revId": "85f6bd8ed5a6d8d35ed81df2bd796e93cdc2d171",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "6d76b098_19dd0e9b",
        "filename": "scripts/acov-llvm.py",
        "patchSetId": 2
      },
      "lineNbr": 196,
      "author": {
        "id": 1043845
      },
      "writtenOn": "2023-09-07T20:42:18Z",
      "side": 1,
      "message": "All of this seems unrelated. Which part of this fixing Python 3.8? What\u0027s the bug?",
      "parentUuid": "922644a5_1b2b851a",
      "revId": "85f6bd8ed5a6d8d35ed81df2bd796e93cdc2d171",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}