{
  "comments": [
    {
      "key": {
        "uuid": "56d538e5_74671203",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1081223
      },
      "writtenOn": "2020-07-15T08:53:08Z",
      "side": 1,
      "message": "I wonder why it didn\u0027t error when I run it...",
      "revId": "df63b55e73b8a34ef577fdddcea7fbf64c83dcb4",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}